# Blockchain by example

version: '2'

services:

  orderer.fsc.com:
    container_name: orderer.fsc.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/fsc.com/orderers/orderer.fsc.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/fsc.com/orderers/orderer.fsc.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.org1.fsc.com:
    container_name: peer0.org1.fsc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.fsc.com
      - CORE_PEER_ADDRESS=peer0.org1.fsc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.fsc.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.fsc.com/peers/peer0.org1.fsc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.fsc.com/peers/peer0.org1.fsc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.fsc.com:
    container_name: peer1.org1.fsc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.fsc.com
      - CORE_PEER_ADDRESS=peer1.org1.fsc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.fsc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.fsc.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.fsc.com/peers/peer1.org1.fsc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.fsc.com/peers/peer1.org1.fsc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053


  peer0.org2.fsc.com:
    container_name: peer0.org2.fsc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.fsc.com
      - CORE_PEER_ADDRESS=peer0.org2.fsc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.fsc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.fsc.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.fsc.com/peers/peer0.org2.fsc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.fsc.com/peers/peer0.org2.fsc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer1.org2.fsc.com:
    container_name: peer1.org2.fsc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.fsc.com
      - CORE_PEER_ADDRESS=peer1.org2.fsc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.fsc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.fsc.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.fsc.com/peers/peer1.org2.fsc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.fsc.com/peers/peer1.org2.fsc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053

  peer0.org3.fsc.com:
    container_name: peer0.org3.fsc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.fsc.com
      - CORE_PEER_ADDRESS=peer0.org3.fsc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.fsc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.fsc.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.fsc.com/peers/peer0.org3.fsc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.fsc.com/peers/peer0.org3.fsc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053

  peer1.org3.fsc.com:
    container_name: peer1.org3.fsc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.fsc.com
      - CORE_PEER_ADDRESS=peer1.org3.fsc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.fsc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.fsc.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.fsc.com/peers/peer1.org3.fsc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.fsc.com/peers/peer1.org3.fsc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12053:7053
